name: Feature Request
description: Suggest a new feature for The Wolf Project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out this form as completely as possible.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Please check existing issues before submitting
      options:
        - label: I have searched the existing issues and this feature has not been requested
          required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this feature solve? Why is it needed?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should be implemented?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternatives...

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this feature fall into?
      options:
        - Gameplay Mechanics
        - New Items (Weapons/Armor)
        - Monsters/Bosses
        - Quests
        - Spells/Skills
        - Client Features
        - Server Performance
        - Administration Tools
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to help implement this feature
        - label: I can help test this feature
        - label: I can help document this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or information about the feature request
